#!/bin/bash

sudo mount --bind /dev "$*/dev"
sudo mount --bind /dev/pts "$*/dev/pts"
sudo mount --bind /proc "$*/proc"
sudo mount --bind /sys "$*/sys"

sudo chroot "$*"

sudo umount "$*/dev/pts"
sudo umount "$*/dev"
sudo umount "$*/proc"
sudo umount "$*/sys"
